### PR TITLE
SITES-5185 - Ensure all GraphQL Queries to publisher are using Persistent Queries and not POST requests

### PR DESCRIPTION
**Pull request by sandru85**
## Description

Disable POST requests for Graphql persisted queries

## Motivation and Context

Immutable files should not be different between SDK and archetype.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by krystiannowak — APPROVED** [review]

**Comment by godanny86** [comment]
@sandru85 you will need to regenerate the MD hash for the immutable file in the pom.xml

**Comment by krystiannowak** [comment]
Thx @godanny86 for a reminder - exactly @sandru85 sth similar as in https://github.com/adobe/aem-guides-wknd/commit/fc34b70622cf047ab5a2fb3c5d27fc4bbf42b22b - you can take archetype after changes in https://github.com/adobe/aem-project-archetype/pull/922 and generate dispatcher's pom.xml and sync hashes from there

**Review by krystiannowak — CHANGES_REQUESTED** [review]
Hashes of immutable files in pom.xml need to be updated - here specifically just one hash of this single changed file.

**Comment by sandru85** [comment]
@krystiannowak @godanny86 I also updated the hashed and the file as in https://github.com/adobe/aem-project-archetype/pull/922

**Comment by godanny86** [comment]
thanks @sandru85 give me some time to merge this. Several of our tutorials use standard POST requests for GraphQL queries.

**Comment by sandru85** [comment]
@godanny86 you can check my comment here https://git.corp.adobe.com/Granite/dispatcher-k8s-base/pull/152#issuecomment-4099643 if you would need to enable the queries on prod

**Comment by sandru85** [comment]
@godanny86 any updates on the validation of this? we would have to get ready and introduce it in the archetyp

**Review by godanny86 — APPROVED** [review]

**Comment by godanny86** [comment]
Thanks @sandru85 looks good, i went ahead and merged.

**Pull request merged**
