### PR TITLE
sync dispatcher immutable files with Dispatcher SDK and image v2.0.166

### PR DESCRIPTION
**Pull request by krystiannowak**
sync dispatcher immutable files with Dispatcher SDK and image v2.0.166

## Description

Since the previous sync of dispatcher immutable files with Dispatcher SDK and image was from version 2.0.120 in August 2022 and AEM CS releases already progressed further, including dispatcher image and SDK tooling containing newer files, it resulted already in customer using latest public AEM CS releases being out of sync and reporting issues like https://github.com/adobe/aem-project-archetype/issues/1043

Hence we propose to sync those files with the ones from the latest Dispatcher SDK and image v2.0.166 in order for validation scripts not to fail in immutable files compatibility check step as described in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/content-delivery/validation-debug.html?lang=en#third-phase

## Related Issue

* https://github.com/adobe/aem-project-archetype/issues/1043
* https://github.com/adobe/aem-project-archetype/pull/1045

## Motivation and Context

Not to fail immutable files validation step described in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/content-delivery/validation-debug.html?lang=en#third-phase when using Dispatcher SDK tooling from the latest AEM CS releases.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by froesef — APPROVED** [review]

**Comment by krystiannowak** [comment]
@SachinMali @davidjgonzalez The changes are currently in Archetype develop via https://github.com/adobe/aem-project-archetype/pull/1045 and will be in Archetype 41 (next to be released)

**Comment by davidjgonzalez** [comment]
@krystiannowak can you re-raise this when 41 is released? WKND stays current to the state of the latest released software (not pre-release, as this is confusing to users that compare their projects using/made from the latest against WKND and see deltas)

**Comment by krystiannowak** [comment]
@davidjgonzalez ok, so since there are no further sync planned for now to Archetype (until 41 is released) we can have it in draft mode, so I can undraft it when 41 is out (as I am not sure what are current Archetype 41 release plans). But if there are any dispatcher config immutable files further sync, I can also propagate them into this PR (e.g. if some other AEM CS release with even newer Dispatcher SDK tooling and dispatcher-publish image is to be released sooner than Archetype).

Hope it works for you?

/cc: @froesef

**Comment by krystiannowak** [comment]
@davidjgonzalez Supposedly now Archetype 41 is being cut, containing that change https://github.com/adobe/aem-project-archetype/milestone/34?closed=1

**Comment by davidjgonzalez** [comment]
@krystiannowak i don't see 41 released yet. Any idea if the release was cancelled?

**Comment by krystiannowak** [comment]
@davidjgonzalez AFAIK it should be out very soon: https://github.com/adobe/aem-project-archetype/releases/tag/untagged-e99e5072ac10d288221b

**Comment by davidjgonzalez** [comment]
@krystiannowak that link 404's - did they rollback the release?

**Comment by SachinMali** [comment]
@krystiannowak Did anyone cut the release, cause I still see 40 on the https://github.com/adobe/aem-project-archetype/releases unless it's getting published, if so once published we should be good for merge.

**Comment by krystiannowak** [comment]
@SachinMali It's still in Draft by @barshat7

**Comment by krystiannowak** [comment]
@davidjgonzalez @SachinMali Archetype 41 is out: https://github.com/adobe/aem-project-archetype/releases

**Review by SachinMali — APPROVED** [review]

**Pull request merged**
