### PR TITLE
Update Adventure Content Fragment Model properties to support new data types and properties

### PR DESCRIPTION
**Pull request by GastonGonzalez**
## Description

Updates to the Adventure Content Fragment Model and related Content Fragments.

## Related Issue

https://github.com/adobe/aem-guides-wknd/issues/231

## Motivation and Context

The Content Fragment Model updates are driven by new Content Fragment Model data type and property changes. The changes included also reflect the model used in the _Modeling Basics_ video as part of the headless video series.

## How Has This Been Tested?

1. All tests were run against the 4/19/21 cloud build
1. Adventure model changes were tested in the Content Fragment Model Editor
1. Existing Adventure Content Fragments were tested in the:
    1. Content Fragment Editor
    2. Rendering on Sites' pages
    3. Rendering on GraphQL  WKND React application

## Types of changes

Breaking changes: 
1. Changed Adventure Group Size  field from Single Line Text to Number
2. Upgraded all Adventure Enumeration types to support new Option Label/Option Value feature
3. Changed Price value from String to Currency and added validation

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
Thanks @GastonGonzalez -- IIRC this is also a breaking change for 6.5.x correct? I dont believe 6.5.x supports these types yet?

**Comment by GastonGonzalez** [comment]
> Thanks @GastonGonzalez -- IIRC this is also a breaking change for 6.5.x correct? I dont believe 6.5.x supports these types yet?

@davidjgonzalez - At the time this PR was created, the enumeration data type changes were not yet back ported to AEM 6.5. These changes were only available in the AEM SDK. I am wondering if you can check back with engineering to see if the latest enumeration data type is available in the latest AEM 6.5 service pack?

**Comment by keepthebyte** [comment]
will be in the next 6.5 SP - 10 - end of August.

**Comment by davidjgonzalez** [comment]
@keepthebyte thanks for the update! we'll hold off till then to merge

**Pull request merged**
